# -*- makefile -*-
CONNNAME=peerB--peerA
ENDNAME=acppeers

TESTNAME=peerB-rI2
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509keys.o
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} OUTPUT/${TESTNAME}.pcap peerA-I1.pcap peerA-I2.pcap peerA-rekeyR1.pcap

PCAPDEPENDENCIES = ../lp121-peerA-I1/OUTPUT/peerA-I1.pcap
PCAPDEPENDENCIES +=../lp123-peerA-I2/OUTPUT/peerA-I2.pcap
PCAPDEPENDENCIES +=../lp131-peerA-rekeyR1/OUTPUT/peerA-rekeyR1.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp121-peerA-I1/OUTPUT/peerA-I1.pcap .
	cp ../lp123-peerA-I2/OUTPUT/peerA-I2.pcap .
	cp ../lp131-peerA-rekeyR1/OUTPUT/peerA-rekeyR1.pcap .

# Local Variables:
# gdb-command: ""
# End Variables:
#

